language: python
python:
  - "3.8"

services:
  - xvfb

install:
  - pip install -r requirements.txt

before_script:
  - python TurnPageRoot/manage.py migrate
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.9/
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=99:0
  - sleep 3

script:
  - black ./
  - flake8 ./
  - coverage run TurnPageRoot/manage.py test bookSwiping.tests

after_success:
  coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "TurnPageDev"
  env: "tp-dev"
  bucket_name: $AWS_BUCKET_NAME
  on:
    repo: gcivil-nyu-org/team-3-inperson
    branch: develop
  skip_cleanup: 'true'
