name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: move_to_root
      run: |
        cd TurnPageRoot
        ls
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip freeze > requirements.txt
        pip install -r requirements.txt
        pip install -e .
    - name: Run Tests
      run: |
        run: python -m pytest --import-mode=append tests/
